# Generated by Django 5.1.2 on 2024-11-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='address')),
                ('lxp', models.IntegerField(default=0, verbose_name='LXP')),
                ('rank', models.IntegerField(default=0, verbose_name='Rank')),
                ('nfts', models.IntegerField(default=0, verbose_name='NFTs')),
            ],
        ),
    ]
